spring:
  application:
    name: capstone1-secure-auth-resilience


resilience4j:
  circuitbreaker:
    circuit-breaker-aspect-order: 2
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        permittedNumberOfCallsInHalfOpenState: 2
        waitDurationInOpenState: 3s
        failureRateThreshold: 50
    instances:
      mockExternalService:
        baseConfig: default
  #        slidingWindowSize: 1
  #        minimumNumberOfCalls: 1
  #        failureRateThreshold: 50
  #        waitDurationInOpenState: 10s

  ratelimiter:
    rate-limiter-aspect-order: 1
    configs:
      default:
       limitForPeriod: 5
       limitRefreshPeriod: 10s
       timeoutDuration: 1s
    instances:
      LoginRateLimiter:
        baseConfig: default


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
    ratelimiter:
      enabled: true