spring:
  application:
    name: capstone1-secure-auth-resilience

resilience4j:
  circuitbreaker:
    circuit-breaker-aspect-order: 1
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 2
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
    instances:
      mockExternalService:
        baseConfig: default
  #        slidingWindowSize: 1
  #        minimumNumberOfCalls: 1
  #        failureRateThreshold: 50
  #        waitDurationInOpenState: 10s

  ratelimiter:
    rate-limiter-aspect-order: 2
    instances:
      loginRateLimiter:
        limitRefreshPeriod: 1s
        limitForPeriod: 2
        timeoutDuration: 1s


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
    ratelimiter:
      enabled: true