spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/capstone_auth
    username: postgres
    password: GunaGagan@1529

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true